services:
  web:
    build: .
    ports:
      - 7952:7952
    volumes:
      - ./config/api-keys.conf:/app/config/api-keys.conf:ro
      - ./logs/logs.txt:/app/logs/logs.txt
    # other settings like ports, etc.